name: Deploy Gold Paper via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Gold Paper para Locaweb
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Enviar arquivos para Locaweb
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ftp.goldpaper1.hospedagemdesites.ws
          username: goldpaper1
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./
          server-dir: ./public_html/
